name: release

on:
  push:
    tags:
    - "v*"

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/ci.yml
    with:
      release: true

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    # Check out with full history to generate release notes.
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Release
      run: gh release create ${{ github.ref_name }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish docs
      run: curl https://proxy.golang.org/github.com/${{ github.repository }}/@v/${{ github.ref_name }}.info
